[book]
title = "Stasis Architecture Book"
authors = ["Tom Vazquez"]
language = "en"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
